### ISSUE TITLE
Custom-Elements, children indents breaking

### ISSUE THREAD

**Issue by quangv** [alvan/vim-closetag#8]
It seems that, the indents of children elements are preserved for known html elements, but gets erased for custom elements.

```
<div>
    <span
</div>
```

after inserting the `>` for span...

```
<div>
    <span></span>
</div>
```

However for custom elements...

```
<custom-div>
    <span
</custom-div>
```

after inserting the `> for span...

```
<custom-div>
<span></span>
</custom-div>
```

**Comment by alvan** [comment]
I think this depends on your indent setting.
Can you try to press "==" to see if the indent is correct?

**Comment by vdumitraskovic** [comment]
I also confirm this bug. Indenting is correct ("==" indents code properly). It is quite annoying when editing JSX file. Any idea how to fix this?

**Comment by nhooyr** [comment]
It is working fine for me. Cannot reproduce.

**Comment by tandrewnichols** [comment]
I'm seeing this as well, although it's in javascript files using jsx, which I'm sure was not an original use case. I'm seeing the opening tag aligned correctly, but the closing tag always aligns with the highest level parent in the file, e.g.

```
return (
    <CustomElement>
        <List>
            <ListItem>
                <div>
                |
    </div>
            </ListItem>
        </List>
    </CustomElement>
)
```

Where `|` is the cursor position. The cursor position is actually never correct for me (when breaking the closing tag to a new line). It always aligns with the element I just added instead of being indented an additional level, e.g.

```
<span>
|
</span>
```

instead of

```
<span>
    |
</span>
```

which is more what I'd expect.

**Comment by alvan** [comment]
This issue won't be fixed.
This is an indentation issue, I have no good solution at present.
And I do think this is NOT a problem that should be solved by this plugin.

**Comment by zacheryph** [comment]
I was getting similar issues to @tandrewnichols.  when I disabled folding I stopped getting the indentation that seemed to make no sense. This is more wierd however cause my other laptop with a similar vimrc and just running an older Vim seems to be just fine.
But I still don't get proper indentation (anywhere) after the second `>`.

Just food for thought
